### ISSUE TITLE
multiprocess issue

### ISSUE THREAD

**Issue by a1953176613** [OdingdongO/pytorch_classification#2]
大佬, 请问一下, 我这个错误是怎么回事啊,  我才刚刚接触pytorch, 很多问题 不懂 , 求指教.

line 83 in train_baidu_xjtu.py and line 41 in  train_util.py.
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by muween** [comment]
在运行代码前加：
`if __name__ == '__main__':`

**Comment by OdingdongO** [comment]
解决了是吧,可能是运行环境不一致.

**Comment by a1953176613** [comment]
解决了非常感谢!
