### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xx674967** [OdingdongO/pytorch_classification#5]
首先非常感谢你提供的代码,我在运行程序时发生如下错误,这个错误是训练到最后才会出现.
不知道怎么解决,期待你的回答.
Traceback (most recent call last):

  File "<ipython-input-1-39361caa3117>", line 1, in <module>
    runfile('/home/xjtubaidu/xjtubaidu/train_baidu_xjtu.py', wdir='/home/xjtubaidu/xjtubaidu')

  File "/home/zz/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/home/zz/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/xjtubaidu/xjtubaidu/train_baidu_xjtu.py", line 83, in <module>
    val_inter=400

TypeError: 'NoneType' object is not iterable

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
这个问题已经解决, 取掉train的返回值即可!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by OdingdongO** [comment]
我没有遇到这个问题,不过我用的Python2.7

**Comment by zhujingsong** [comment]
我也遇到这个情况了：就是快要训练完到最后成这样了。。。我是python2.7
2018-05-09 16:41:28 [49-479] | batch-loss: 0.238 | acc@1: 1.000
2018-05-09 16:41:35 [49-529] | batch-loss: 0.013 | acc@1: 1.000
Traceback (most recent call last):
  File "train_main.py", line 83, in <module>
    val_inter=400,
TypeError: 'NoneType' object is not iterable

但是影响不大，因为参数基本都保存下来了。。。

我查了一下，感觉应该 train_main.py 最后一句有点小问题：
best_acc,best_model_wts = train(model,
                                  epoch_num=50,
                                  start_epoch=0,
                                  optimizer=optimizer,
                                  criterion=criterion,
                                  exp_lr_scheduler=exp_lr_scheduler,
                                  data_set=data_set,
                                  data_loader=dataloader,
                                  save_dir=save_dir,
                                  print_inter=50,
                                  val_inter=400,
                                  )
这里调用了 train_util.py 里面定义的 train()函数，但是train ()里面好像没有 return best_acc,best_model_wts，所以训练到最后就变成 'NoneType' object 没有返回
（调用时，将None赋给多个值时，会出现提示：TypeError: 'NoneType' object is not iterable）
参考：http://www.jb51.net/article/102803.htm
但是影响不大，应该历史记录各个阶段的.pth文件都保存下来了

最后，说的不对勿怪，菜鸟一枚，感谢up主大大的代码，学到很多东西。。。。。。

**Comment by xx674967** [comment]
@OdingdongO  
恩,很奇怪,我python 2 3 都试过,pytorch 0.3 0.3.1 0.4 也试了...  
总之 感谢你的回答. 我自己再研究研究吧

**Comment by xx674967** [comment]
@zhujingsong 对,我也这样觉得,可是up主完全没问题,版本什么的都一样,就是不知道问题在哪.

**Comment by 2018daofeng** [comment]
@zhujingsong  你的训练数据可以保存？

**Comment by struggling-man** [comment]
这个问题我之前也遇到过，就是想楼上说的是因为没有train中没有返回值造成的，把best_acc,best_model_wts = 去掉不要返回就不会报这个错误了

**Comment by 2018daofeng** [comment]
![image](https://user-images.githubusercontent.com/38021668/39953064-c5ea15ca-55d5-11e8-9248-9093d713ad71.png)
为什么是0？

**Comment by struggling-man** [comment]
因为你测试集本身就不知道对错啊

**Comment by WilyZhao8** [comment]
各位好，我想请教个问题：就是在训练的时候acc@1为什么不是0.000就是1.000？看代码感觉没什么问题啊？

**Comment by OdingdongO** [comment]
有可能是这样的,因为我程序都会在中途kill掉,所以没注意这个问题

**Comment by xx674967** [comment]
@OdingdongO  正确答案就是 @struggling-man  说的, train 去掉返回值即可.

**Comment by 2018jack** [comment]
struggling-man 我是用train之后的模型和参数进行测试的，只不过最后的.pth是[0000],我感觉是参数没有写进去吧。

**Comment by 2018daofeng** [comment]
@struggling-man   
![image](https://user-images.githubusercontent.com/38021668/40003121-1547b424-57c5-11e8-898d-3e7d3c556a8e.png)
我用的就是train之后的.pth文件,我觉得我训练的数据没有成功，weights-49-429-[0.0000]，这里面都是零？好奇怪。

**Comment by OdingdongO** [comment]
已更新
