### ISSUE TITLE
数据扩增问题

### ISSUE THREAD

**Issue by youngYMR** [OdingdongO/pytorch_classification#6]
请问数据集有扩增吗？看代码的话，只是单纯的对图片做了变化。

**Comment by struggling-man** [comment]
有没有做数据扩增的，就是旋转，平移，对比度这些吗，扩增后直接自己命名加标签？

**Comment by xx674967** [comment]
代码里属于常规的数据增强吧, 至于扩增,感觉会比较麻烦.....

**Comment by OdingdongO** [comment]
代码里只做了常规的线上扩增,包含随机旋转和随机剪裁.
这个比赛数据预处理还是挺重要的
